version: '3.8'

services:
  app:
    build: .
    container_name: project-capstone-app
    ports:
      - "6979:80"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=certificate
      - DB_USER=root
      - DB_PASS=root

  db:
    image: mysql:5.7
    container_name: project-capstone-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: certificate
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:

